### ISSUE TITLE
Release Tasks

### ISSUE THREAD

**Issue by pyrello** [uiowa/uiowa01#6]
This issue is for tracking all the tasks that we need to do to get ready for a stable release. It is meant to be a quick way to add tasks or ideas for tasks without having to create an issue right away. Feel free to edit this issue directly to add/remove tasks. Add separate comments for discussion.

### Content Types
- [x] Basic page - Currently included in Lightning, do we need to modify?
- [x] #7: Article 
- [x] #9: Event
- [x] Person/Profile/Author - [Discussion about person-related content types](https://github.com/uiowa/uiowa01/issues/10). This might need to be split into multiple tasks.

### Content Fragments
These are non-node entities. They do not require a path, but should work with revisioning.
- [x] [Meta] #14: Discussion about how to handle custom block types with multiple content fragment embedded in them.
- [x] #11: Noteworthy/Feature
- [ ] Carousel Slide

### Miscellaneous
- [x] #8: Create basic profile for spinning up sites for testing the theme and feature module generation.
- [ ] Test different site updating configuration scenarios.
- [ ] Implement a travis.yml file for automating checks.
- [ ] Documentation - this should probably be it's own category.
- [ ] Implement responsive images application-wide.
- [x] #16: Change the name of collegiate_theme_base to something less confusing.

[Collegiate task tracker](https://github.com/uiowa/collegiate/issues/4)

**Comment by bspeare** [comment]
I have put together a separate extended content type & content fragment inventory here: https://github.com/uiowa/uiowa01/issues/66#issuecomment-519254541

**Comment by pyrello** [comment]
Since we have pretty much all of this covered in other issues, I'm going to close this.
